version: '3.8'

services:
  sip-agent:
    image: ghcr.io/${GITHUB_REPOSITORY:-sip-ai-agent}:${VERSION:-latest}
    container_name: sip-ai-agent-prod
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8080:8080"      # Web UI Dashboard
      - "9090:9090"      # Prometheus metrics
      - "5060:5060/udp"  # SIP signaling
      - "16000-16100:16000-16100/udp"  # RTP media
    environment:
      - TZ=UTC
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/healthz', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - sip-network

  web:
    image: ghcr.io/${GITHUB_REPOSITORY:-vaheed/sip-ai-agent}-web:${VERSION:-latest}
    container_name: sip-ai-web-prod
    restart: unless-stopped
    ports:
      - "8081:8080"      # Web UI Dashboard (different port for prod)
    depends_on:
      sip-agent:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - sip-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: sip-ai-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
      - sip-agent
    networks:
      - sip-network

  # Optional: Add a database for persistent call history
  postgres:
    image: postgres:15-alpine
    container_name: sip-ai-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=sip_ai_agent
      - POSTGRES_USER=sip_agent
      - POSTGRES_PASSWORD=${DB_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - sip-network

  # Optional: Add Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: sip-ai-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - sip-network

volumes:
  postgres_data:
  redis_data:

networks:
  sip-network:
    driver: bridge
