version: '3.8'

services:
  sip-agent:
    image: ghcr.io/${GITHUB_REPOSITORY:-vaheed/sip-ai-agent}:${VERSION:-latest}
    container_name: sip-ai-agent-prod
    restart: unless-stopped
    volumes:
      - sip_ai_logs:/app/logs
      - sip_ai_data:/app/data
    env_file:
      - .env
    ports:
      - "8080:8080"      # Web UI Dashboard
      - "9090:9090"      # Prometheus metrics
      - "5060:5060/udp"  # SIP signaling
      - "16000-16100:16000-16100/udp"  # RTP media
    environment:
      - TZ=UTC
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - sip-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  web:
    image: ghcr.io/${GITHUB_REPOSITORY:-vaheed/sip-ai-agent}-web:${VERSION:-latest}
    container_name: sip-ai-web-prod
    restart: unless-stopped
    ports:
      - "8081:8080"      # Web UI Dashboard (different port for prod)
    depends_on:
      sip-agent:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - sip-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

  # Optional: Add a reverse proxy for production (if you want to expose on port 80/443)
  # nginx:
  #   image: nginx:1.25-alpine
  #   container_name: sip-ai-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - web
  #     - sip-agent
  #   networks:
  #     - sip-network
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128M
  #         cpus: '0.25'
  #       reservations:
  #         memory: 64M
  #         cpus: '0.1'

volumes:
  sip_ai_logs:
    driver: local
  sip_ai_data:
    driver: local

networks:
  sip-network:
    driver: bridge
